name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    - name: Restore dependencies
      run: dotnet restore TodoApp/TodoApp.csproj

    - name: Build
      run: dotnet build TodoApp/TodoApp.csproj --no-restore

    - name: Test
      run: dotnet test TodoApp/TodoApp.csproj --no-build
